---
title: " R Packages 2024 list so far"
author: "Giorgio Luciano"
date: "2024-06-19"
categories: 
  - R
  - packages
editor: 
  markdown: 
    wrap: 72
---

1.  List of packages I've found useful in my workflow during 2024 (so
    far)

## Plot

### **spiralize: Visualize Data on Spirals**

*tags*: #plot\
\[cran package link\] <https://CRAN.R-project.org/package=spiralize>

*description from the author/vignette*\

> It visualizes data along an Archimedean spiral
> <https://en.wikipedia.org/wiki/Archimedean_spiral>, makes so-called
> spiral graph or spiral chart. It has two major advantages for
> visualization: 1. It is able to \>visualize data with very long axis
> with high resolution. 2. It is efficient for time series data to
> reveal periodic patterns.

### **panelView: Visualizing Panel Data**

*tags*: #plot\
\[cran package link\] <https://CRAN.R-project.org/package=panelView>

*description from the author/vignette*\

> Visualizes panel data. It has three main functionalities: (1) it plots
> the treatment status and missing values in a panel dataset; (2) it
> visualizes the temporal dynamics of a main variable of interest; (3)
> it depicts the bivariate relationships between a treatment variable
> and an outcome variable either by unit or in aggregate. For details,
> see <doi:10.18637/jss.v107.i07>.

## Spectroscopy

### **OpenSpecy: Analyze, Process, Identify, and Share Raman and (FT)IR Spectra**

*tags*: #spectroscopy\
\[cran package link\] <https://CRAN.R-project.org/package=OpenSpecy>

*description from the author/vignette*\

> Raman and (FT)IR spectral analysis tool for plastic particles and
> other environmental samples (Cowger et al. 2021,
> <doi:10.1021/acs.analchem.1c00123>). With read_any(), Open Specy
> provides a single function for reading individual, batch, or map
> spectral data files like .asp, .csv, .jdx, .spc, .spa, .0, and .zip.
> process_spec() simplifies processing spectra, including smoothing,
> baseline correction, range restriction and flattening, intensity
> conversions, wavenumber alignment, and min-max normalization. Spectra
> can be identified in batch using an onboard reference library (Cowger
> et al. 2020, <doi:10.1177/0003702820929064>) using match_spec(). A
> Shiny app is available via run_app() or online at\>
> <https://openanalysis.org/openspecy/>.

### **plsVarSel: Variable Selection in Partial Least Squares**

*tags*: #pls #partial least squares #regression\
\[cran package link\] <https://CRAN.R-project.org/package=plsVarSel>

*description from the author/vignette*\

> Interfaces and methods for variable selection in Partial Least
> Squares. The methods include filter methods, wrapper methods and
> embedded methods. Both regression and classification is supported.

## Statistics

### **qreport: Statistical Reporting with 'Quarto'**

*tags*: #statistics\
\[cran package link\] <https://CRAN.R-project.org/package=qreport>

*description from the author/vignette*\

> Provides statistical components, tables, and graphs that are useful in
> 'Quarto' and 'RMarkdown' reports and that produce 'Quarto' elements
> for special formatting such as tabs and marginal notes and graphs.
> Some of the functions produce entire report sections with tabs, e.g.,
> the missing data report created by missChk(). Functions for inserting
> variables and tables inside 'graphviz' and 'mermaid' diagrams are
> included, and so are special clinical trial graphics for adverse event
> reporting.

### **sjPlot: Data Visualization for Statistics in Social Science**

*tags*: #statistics #social science \[cran package link\]
<https://CRAN.R-project.org/package=sjPlot>

*description from the author/vignette*\

> Collection of plotting and table output functions for data
> visualization. Results of various statistical analyses (that are
> commonly used in social sciences) can be visualized using this
> package, including simple and cross tabulated frequencies, histograms,
> box plots, (generalized) linear models, mixed effects models,
> principal component analysis and correlation matrices, cluster
> analyses, scatter plots, stacked scales, effects plots of regression
> models (including interaction terms) and much more. This package
> supports labelled data.

### **MVET: Multivariate Estimates and Tests**

*tags*: #statistics\
\[cran package link\] <https://CRAN.R-project.org/package=MVET>

*description from the author/vignette*\

> Multivariate estimation and testing, currently a package for testing
> parametric data. To deal with parametric data, various multivariate
> normality tests and outlier detection are performed and visualized
> using the 'ggplot2' package. Homogeneity tests for covariance matrices
> are also possible, as well as the Hotelling's T-square test and the
> multivariate analysis of variance test. We are exploring additional
> tests and visualization techniques, such as profile analysis and
> randomized complete block design, to be made available in the future
> and making them easily accessible to users.

### **pbox: Exploring Multivariate Spaces with Probability Boxes**

*tags*: #statistics\
\[cran package link\] <https://CRAN.R-project.org/package=pbox>

*description from the author/vignette*\

> Advanced statistical library offering a method to encapsulate and
> query the probability space of a dataset effortlessly using
> Probability Boxes (p-boxes). Its distinctive feature lies in the ease
> with which users can navigate and analyze marginal, joint, and
> conditional probabilities while taking into account the underlying
> correlation structure inherent in the data using copula theory and
> models. A comprehensive explanation is available in the paper "pbox:
> Exploring Multivariate Spaces with Probability Boxes" to be published
> in the Journal of Statistical Software.

### **equatiomatic: Transform Models into 'LaTeX' Equations**

*tags*: #statistics #latex #regression #models\
\[cran package link\] <https://CRAN.R-project.org/package=equatiomatic>

*description from the author/vignette*\

> The goal of 'equatiomatic' is to reduce the pain associated with
> writing 'LaTeX' formulas from fitted models. The primary function of
> the package, extract_eq(), takes a fitted model object as its input
> and returns the corresponding 'LaTeX' code for the model.

### **bulkreadr: The Ultimate Tool for Reading Data in Bulk**

*tags*: #bulk import\
\[cran package link\] <https://CRAN.R-project.org/package=bulkreadr>

*description from the author/vignette*\

> Designed to simplify and streamline the process of reading and
> processing large volumes of data in R, this package offers a
> collection of functions tailored for bulk data operations. It enables
> users to efficiently read multiple sheets from Microsoft Excel and
> Google Sheets workbooks, as well as various CSV files from a
> directory. The data is returned as organized data frames, facilitating
> further analysis and manipulation. Ideal for handling extensive data
> sets or batch processing tasks, bulkreadr empowers users to manage
> data in bulk effortlessly, saving time and effort in data preparation
> workflows. Additionally, the package seamlessly works with labelled
> data from SPSS and Stata.

## Simulated data

### **rsurv: Random Generation of Survival Data**

*tags*: #rsurv\
\[cran package link\] <https://CRAN.R-project.org/package=rsurv>

*description from the author/vignette*\

> Random generation of survival data from a wide range of regression
> models, including accelerated failure time (AFT), proportional hazards
> (PH), proportional odds (PO), accelerated hazard (AH), Yang and
> Prentice (YP), and extended hazard (EH) models. The package 'rsurv'
> also stands out by its ability to generate survival data from an
> unlimited number of baseline distributions provided that an
> implementation of the quantile function of the chosen baseline
> distribution is available in R. Another nice feature of the package
> 'rsurv' lies in the fact that linear predictors are specified via a
> formula-based approach, facilitating the inclusion of categorical
> variables and interaction terms. The functions implemented in the
> package 'rsurv' can also be employed to simulate survival data with
> more complex structures, such as survival data with different types of
> censoring mechanisms, survival data with cure fraction, survival data
> with random effects (frailties), multivariate survival data, and
> competing risks survival data. Details about the R package 'rsurv' can
> be found in Demarqui (2024) <doi:10.48550/arXiv.2406.01750>.

## Reporting and Formatting

### **ftExtra: Extensions for 'Flextable'**

*tags*: #tables #flextables\
\[cran package link\] <https://CRAN.R-project.org/package=ftExtra>

*description from the author/vignette*\

> Build display tables easily by extending the functionality of the
> 'flextable' package. Features include spanning header, grouping rows,
> parsing markdown and so on.

## Fun

### **PlayerChart: Generate Pizza Chart: Player Stats 0-100**

*tags*: #statistics  \[cran package link\]
<https://CRAN.R-project.org/package=PlayerChart>

*description from the author/vignette*\

> Create an interactive pizza chart visualizing a specific player's
> statistics across various attributes in a sports dataset. The chart is
> constructed based on input parameters: 'data', a dataframe containing
> player data for any sports; 'player_stats_col', a vector specifying
> the names of the columns from the dataframe that will be used to
> create slices in the pizza chart, with statistics ranging between 0
> and 100; 'name_col', specifying the name of the column in the
> dataframe that contains the player names; and 'player_name',
> representing the specific player whose statistics will be visualized
> in the chart, serving as the chart title.

### **gameR: Color Palettes Inspired by Video Games**

*tags*: #statistics  \[cran package link\]
<https://CRAN.R-project.org/package=gameR>

*description from the author/vignette*\

> Palettes based on video games.
