project:
  type: website
  output-dir: docs
website:
  title: "Fun with Data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/giorgioluciano
      - icon: twitter
        href: https://twitter.com/giorgioluciano
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

