project:
  type: website
  output-dir: docs
website:
  title: "Giorgio Luciano"
  navbar:
    left: 
      - text: Code
        file: listing.qmd
      - text: CrystalNodes  
        href: https://github.com/giorgioluciano/CrystalNodes
    right:
      - icon: github
        href: https://github.com/giorgioluciano
      - icon: twitter
        href: https://twitter.com/giorgioluciano
      - icon: linkedin
        href: https://www.linkedin.com/in/giorgioluciano/
      - icon: instagram
        href: https://www.instagram.com/giorgioluciano5477/
      - icon: behance
        href: https://www.behance.net/giorgioluciano
      - icon: stickies
        href: https://www.giorgioluciano.co.place
cookie-consent: true        
format:
  html:
    theme: 
      light: flatly
      dark: darkly
     css: styles.css

editor: visual

