project:
  type: website
  output-dir: docs
website:
  title: "R, Python, Data and Spaghetti code"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/giorgioluciano
      - icon: twitter
        href: https://twitter.com/giorgioluciano
      - icon: linkedin
        href: https://github.com/giorgioluciano  
format:
  html:
    theme: simplex
    css: styles.css

editor: visual

