project:
  type: website
  output-dir: docs
website:
  title: "Giorgio Luciano"
  site-url: https://giorgioluciano.github.io
  navbar:
    left: 
      - text: Code
        file: listing.qmd
      - text: CrystalNodes  
        href: https://github.com/giorgioluciano/CrystalNodes
    right:
      - icon: github
        href: https://github.com/giorgioluciano
      - icon: twitter
        href: https://twitter.com/giorgioluciano
      - icon: linkedin
        href: https://www.linkedin.com/in/giorgioluciano/
      - icon: instagram
        href: https://www.instagram.com/giorgioluciano5477/
      - icon: behance
        href: https://www.behance.net/giorgioluciano
    - icon: rss
        href: index.xml
cookie-consent: true        
format:
  html:
    toc: true
    theme:
      light: [trestles, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
  
editor: visual

