project:
  type: website
  output-dir: docs
website:
  title: "giorgioluciano.github.io"
  site-url: https://giorgioluciano.github.io
  description: "Provides tutorials  alongside practical examples in R. Topics include statistical simulations, data visualization, and common challenges in scientific analysis. The content is designed to offer useful insights for those working with data, without unnecessary complexity."
  
  navbar:
    left: 
      - text: Code
        file: listing.qmd
      - text: CrystalNodes  
        href: https://github.com/giorgioluciano/CrystalNodes
      - text: ESGT
        href: https://github.com/giorgioluciano/ESGT/
    right:
      - icon: github
        href: https://github.com/giorgioluciano
      - icon: twitter
        href: https://twitter.com/giorgioluciano
      - icon: linkedin
        href: https://www.linkedin.com/in/giorgioluciano/
      - icon: instagram
        href: https://www.instagram.com/giorgioluciano5477/
      - icon: behance
        href: https://www.behance.net/giorgioluciano
      - icon: rss
        href: index.xml


  

cookie-consent: true        
format:
  html:
    toc: true
    theme:
      light: [trestles, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
  
editor: visual

